### ISSUE TITLE
Pricing would be useful with getVMSizes() 

### ISSUE THREAD

**Issue by gjwgit** [Azure/AzureDSVM#14]
The Azure console lists the estimated pricing for the DSVM on creation. This is useful in deciding the machine size at that time. This enhancement suggestion is to include this same pricing estimate from getVMSizes() so as to provide information to assist in deciding the VM size.

**Comment by yueguoguo** [comment]
It is a desired feature but at the moment it is hard to do so because pricing depends on subscription so it may vary from account to account.
